name: CI_ubuntu

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
        tar -xvzf ngrok.tgz
        chmod +x ngrok

    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install xrdp
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set xrdp password
      run: echo -e "P@ssw0rd!\nP@ssw0rd!" | sudo passwd $USER

    - name: Create TCP Tunnel
      run: ./ngrok tcp 3389
